server:
  port: 8082
aws:
  s3:
    endpoint: http://localhost:4566
    accessKeyId: 7387057044
    secretAccessKey: Pass@9049

  file transfer:
  bucketName: uploads
  sourceFolder: source/
  destinationFolder: destination/